name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout repository
      uses: actions/checkout@v3

    # Login to Docker Hub
    - name: Log in to Docker Hub
      run: echo "Venky@460" | docker login -u "VenkateshPulibandla" --password-stdin

    # Build Docker image
    - name: Build Docker Image
      run: docker build -t VenkateshPulibandla/ecommerce:latest .

    # Push Docker image to Docker Hub
    - name: Push Docker Image
      run: docker push VenkateshPulibandla/ecommerce:latest
